/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 earth.gltf 
Author: PatelDev (https://sketchfab.com/PatelDev)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/earth-f7a76c63ff1846afb2d606e5c8369c15
Title: Earth
*/
import React, { useRef } from 'react'
import { useFrame } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/earth.gltf')
  const earthRef = useRef()

  // Rotate the Earth model continuously
  useFrame(() => {
    if (earthRef.current) {
      earthRef.current.rotation.y += 0.003 // Adjust the speed of rotation here
    }
  })

  return (
    <group ref={earthRef} {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials['Scene_-_Root']} scale={2.5} />
    </group>
  )
}

useGLTF.preload('/earth.gltf')
